name: BedWars2023-Ratio
version: ${project.version}
authors: [itz_leoo, OXipro]
main: com.oxipro.bedwars.ratio.Main
description: BedWars2023 Ratio stats Addon
depend:
  - PlaceholderAPI
softdepend:
  - BedWars2023
  - BWProxy2023